### PR TITLE
Bundle libflatpak

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**

### CODE REVIEW

**Comment by aaronfranke** [comment]
@TheEvilSkeleton Thanks for contributing! This PR will have to be rebased and re-tested for it to be considered, because of the release of Warehouse 2.0 conflicting with it.

**Comment by TheEvilSkeleton** [comment]
Done

**Comment by aaronfranke** [comment]
This is failing the formatting CI check, can you run the formatter? The instructions are in the README file.

**Comment by TheEvilSkeleton** [comment]
> This is failing the formatting CI check, can you run the formatter? The instructions are in the README file.

Thanks, it seems to work now

**Pull request merged**
