### PR TITLE
Update es.po

### PR DESCRIPTION
**Pull request by IngrownMink4**
### I have made the following changes:
- I have changed some terminology (for example, remover -> eliminar)
- I have improved the consistency of some text strings.
- I have fixed the extra spaces in some of the translated strings
- I have adapted some strings to the terminology of GNOME

P.S. I would appreciate it if the first translator could also give his approval (I think it is @R4csu btw)

### CODE REVIEW

**Comment by heliguy4599** [comment]
I thank you very much for your interest and work on my app, but unfortunately, as stated in the readme, Warehouse is currently not accepting any new translations until better and more proper translation infrastructure is in place. Again thanks for your efforts but we cannot accept them as of right now. Feel free to translate again in around 3 months if you still feel like doing so tho!

**Comment by IngrownMink4** [comment]
> I thank you very much for your interest and work on my app, but unfortunately, as stated in the readme, Warehouse is currently not accepting any new translations until better and more proper translation infrastructure is in place. Again thanks for your efforts but we cannot accept them as of right now. Feel free to translate again in around 3 months if you still feel like doing so tho!

Oh, I didn't know that. Okay, don't worry, I will translate it again. Thanks for the clarification!

**Comment by R4csu** [comment]
Hi @IngrownMink4, the new translation infrastructure is out, I translate most of it but your corrections to fit better the terminology of GNOME or other stuff could be really appreciated in this new translations, you did an amazing work here!

https://weblate.fyralabs.com/projects/flattool/warehouse/

**Comment by IngrownMink4** [comment]
I have already seen that you and [@oscfdezdz](https://weblate.fyralabs.com/user/oscfdezdz/) have already completed all the text strings. Thanks for taking care of it :D

**Comment by heliguy4599** [comment]
Oh hi just saw this thread was still going. Thank you Racsu for sharing that information and for IngrownMink for their continued interest!

**Pull request closed without merging**
