### PR TITLE
Add Turkish translation

### PR DESCRIPTION
**Pull request by sabriunal**
Because of the new strings introduced in my previous merge request, I was unable to send them through the translation platforms.

### CODE REVIEW

**Comment by heliguy4599** [comment]
Hi! Thanks for your interests and efforts in translation, I very much appreciate it. But unfortunately, I cannot accept translations done outside of the Weblate as doing so seriously messes up the Weblate, which requires time for me to fix, and potential loss of work from other translators (I know from experience). I do have good news! Since I've merged your previous request, you should be able to use the Weblate to translate now. I hope that isn't too much to ask, and once again, thank you.

**Comment by sabriunal** [comment]
I will send via Weblate. I just archived my translation. thanks.

**Comment by runarcn** [comment]
@heliguy4599 close this?

**Comment by sabriunal** [comment]
Yes, thanks.

**Pull request closed without merging**
